# Generated by Django 4.1.2 on 2022-10-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niral', '0002_portfolio_delete_protfolio_alter_home_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
