# Generated by Django 4.1.2 on 2022-10-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niral', '0003_alter_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=200),
        ),
    ]
