# Generated by Django 4.1.2 on 2022-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niral', '0004_alter_about_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
