# Generated by Django 4.1.2 on 2022-10-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niral', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
